<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<?php 
$orderId=$block->getOrderId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order = $objectManager->create('\Magento\Sales\Model\OrderRepository')->get($orderId);
/*echo '<pre>';
print_r($order->getBillingAddress()->getData());  
echo "-----------------";
echo '<pre>';
print_r($order->getShippingAddress()->getData()); 
exit; 
*/
$json['channel_type']='offline';
$json['instructions']='my test';
$json['marketplace_order_id']=$orderId;
$json['shipping_type']='salasa_shipping';
$json['shipment_service_level']='';

$json['billing_address']['billing_email_id']=$order->getBillingAddress()->getData()['email'];
$json['billing_address']['billing_company_name']='salasa';
$json['billing_address']['billing_name']=$order->getBillingAddress()->getData()['firstname'].' '.$order->getBillingAddress()->getData()['lastname'];
$json['billing_address']['billing_address_1']=$order->getBillingAddress()->getData()['region'];
$json['billing_address']['billing_address_2']=$order->getBillingAddress()->getData()['street'];
$json['billing_address']['billing_address_3']=$order->getBillingAddress()->getData()['city'];
$json['billing_address']['billing_city']=$order->getBillingAddress()->getData()['city'];
$json['billing_address']['billing_district']=$order->getBillingAddress()->getData()['city'];
$json['billing_address']['billing_state']=$order->getBillingAddress()->getData()['region'];
$json['billing_address']['billing_pincode']=$order->getBillingAddress()->getData()['postcode'];
$json['billing_address']['billing_mobile_no']=$order->getBillingAddress()->getData()['telephone'];
$json['billing_address']['billing_country']=$order->getBillingAddress()->getData()['country_id'];

$json['receiver_address']['receiver_email_id']=$order->getBillingAddress()->getData()['email'];
$json['receiver_address']['receiver_company_name']='salasa';
$json['receiver_address']['receiver_name']=$order->getBillingAddress()->getData()['firstname'].' '.$order->getBillingAddress()->getData()['lastname'];
$json['receiver_address']['receiver_address_1']=$order->getBillingAddress()->getData()['region'];
$json['receiver_address']['receiver_address_2']=$order->getBillingAddress()->getData()['street'];
$json['receiver_address']['receiver_address_3']=$order->getBillingAddress()->getData()['city'];
$json['receiver_address']['receiver_city']=$order->getBillingAddress()->getData()['city'];
$json['receiver_address']['receiver_district']=$order->getBillingAddress()->getData()['city'];
$json['receiver_address']['receiver_state']=$order->getBillingAddress()->getData()['region'];
$json['receiver_address']['receiver_pincode']=$order->getBillingAddress()->getData()['postcode'];
$json['receiver_address']['receiver_mobile_no']=$order->getBillingAddress()->getData()['telephone'];
$json['receiver_address']['receiver_country']=$order->getBillingAddress()->getData()['country_id'];
$json['payment_details']['payment_method']='prepaid';
$json['order_amount']['price']=(int)$order->getGrandTotal();
$json['order_amount']['currency_code']=$order->getOrderCurrencyCode();
$json['tracking_details']['shipping_partner_id']='';
//$json['tracking_details']['shipping_partner_id']='';
$i=0;
$items=[];
foreach ($order->getAllItems() as $item)
{
    $items[$i]['sku_id']=$item->getSku(); 
	$items[$i]['title']=$item->getName();
	$items[$i]['item_quantity']=(int)$item->getQtyOrdered();; 
    $items[$i]['fulfill_inventory_bucket']='in_available';	
    $items[$i]['item_amount']=(int)$item->getPrice();	
 
	$i++;
}
 $json['order_line_items']=$items;
 $payloads['data']=$json;
 $payload = json_encode($payloads);
 $ch = curl_init();       
 curl_setopt($ch, CURLOPT_URL,'https://staging-salasa-api-public.eunimart.com/api/v2/order_management/whole_order/create');
 curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
 curl_setopt($ch, CURLOPT_HEADER, FALSE);
 curl_setopt($ch, CURLOPT_POST, TRUE);
 curl_setopt($ch, CURLOPT_POSTFIELDS,$payload);
 curl_setopt($ch, CURLOPT_HTTPHEADER, array(
          "Content-Type: application/json",
		  "Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZGE4ZDBjZTQtMzU3MS00MjgxLWE4MDctZDAyNDExOThlZmEzIiwidXNlcl9uYW1lIjoici5sdWx1MiIsImVtYWlsX2lkIjoici5sdWx1MkBzYWxhc2EuY28iLCJmaXJzdF9uYW1lIjoici5sdWx1MiIsImxhc3RfbmFtZSI6InIubHVsdTIiLCJhY2NvdW50X2lkIjoiYWQ3MTA3OTYtZjg2Mi00MWY2LThjNTAtZWIxNWVjMDczZDA5IiwiY2xpZW50X2NvZGUiOiJURVNUMSIsImp0aSI6IjU4YzYzODcxLWM2N2EtNDliNS1iMTJlLTgwNDkwZDU1OThkNyIsIm5ld191c2VyIjpmYWxzZSwiaWF0IjoxNjI1MDU3MjI2LCJleHAiOjE2NTY1OTMyMjYsImF1ZCI6IjB5cDE1N3ltZDQiLCJpc3MiOiJ2ZGV6aV9kZXZlbG9wZXJfc2V0dGluZ3NfbWFuYWdlbWVudCJ9.kpkCGN8_gaDRx-MdON1Gpynb_ZEvPZDlsBC4owTQ96E",
		  "x-api-key : ZGE4ZDBjZTQtMzU3MS00MjgxLWE4MDctZDAyNDExOThlZmEz",
        ));
 $response = curl_exec($ch);
		
 $res=json_decode($response,TRUE);

  if($res['status']=="1"){
	   $salasa_order_id=$res['data']['order_id'];
	   $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
       $connection = $resource->getConnection();
	   $tableName = $resource->getTableName('sales_order'); //gives table name with 
		//Update Data into table
	   $sql = "Update " . $tableName . " Set salasa_order_id = '".$salasa_order_id."' where entity_id = '".$orderId."'";
	   $connection->query($sql);
  }
 curl_close($ch);
?>

<div class="checkout-success">
    <?php if ($block->getOrderId()) :?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
        <?php  else :?>
            <p><?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif;?>
            <p><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>
</div>
